### ISSUE TITLE
latest verstion 1.0.1 doesn't work with basic example: Uncaught TypeError: syncHistory is not a function

### ISSUE THREAD

**Issue by StevenIseki** [rackt/redux-simple-router#157]
I have just tested the [basic example](https://github.com/rackt/redux-simple-router/tree/master/examples/basic), installing the latest version `"redux-simple-router": "1.0.1"`

It gives the following error: **Uncaught TypeError: syncHistory is not a function**

It seems that the lib from version **1.0.1** is not up to date with the current src. If I run `npm run build` and then use index.js from lib, it works fine.

I can see in the following commit: this is where syncReduxAndRouter function has changed to syncHistory: https://github.com/rackt/redux-simple-router/commit/6fc6ab7a5fd29cf8cb7ab0f39a528a10cdc30d5f#diff-1fdf421c05c1140f6d71444ea2b27638

Now that I look at the latest published date on npm is 2 weeks ago, so obviously this recent version is not published. Can we publish it as soon as its all good and tested, otherwise the basic example is incorrect at the moment.

Thanks

**Comment by kjbekkelund** [comment]
Here's the example for the 1.0.2 tag: https://github.com/rackt/redux-simple-router/tree/1.0.2/examples/basic

(The example in master has changed, as we're working on ideas for 2.0)

**Comment by StevenIseki** [comment]
cool thanks.

If version 1.0.2 is the current stable version, maybe the basic example should stay up to date with it similar to as you mentioned the README is still for 1.0.2. Just as its the official example people will start off with. I'm not sure, I just imagine lots of people running into this issue and also the `pushPath()` issue while you are working on 2.0

Actually maybe a note on the basic example [README](https://github.com/rackt/redux-simple-router/blob/master/examples/basic/README.md) pointing to the 1.0.2 tag while 2.0 is being developed could solve the problem easier.

Anyways thanks for that, I will keep using 1.0.2 for now

**Comment by timjackleus** [comment]
I'm trying to to get started with the basic example as well but stuck with the same error (Uncaught TypeError: syncHistory) even on 1.0.2.

**Comment by ChristopherRabotin** [comment]
@timjackleus there is no `syncHistory` in the basic example linked above. Check that you don't have old code lying around.
