### ISSUE TITLE
example with react-router 2.x

### ISSUE THREAD

**Issue by bdefore** [rackt/redux-simple-router#181]
Does the latest version 2.0.1 work with react router 2.0.0-rc4? Is there an example for how to get this to work?

**Comment by bdefore** [comment]
My attempt to get this to work with my universal-redux npm library (https://github.com/bdefore/universal-redux) is not working. Following along the example in this repo (which works with react-router 1.0.0) I'm attempting to apply `syncHistory` to the new 2.0 instance of `browserHistory`

I'm setting up my reducers, including `routing: routeReducer` here: https://github.com/bdefore/universal-redux/blob/master/examples/jwt/src/redux/modules/index.js#L9

This then gets passed to the client here in the import of reducers here: https://github.com/bdefore/universal-redux/blob/master/src/client.js#L11

At which point my createStore helper assembles the middleware: https://github.com/bdefore/universal-redux/blob/master/src/shared/create.js

But when I load up my app, `path` is not available in `props`

**Comment by bdefore** [comment]
I've updated my JWT example to be a good base to investigate: https://github.com/bdefore/universal-redux/tree/master/examples/jwt

When running `npm run dev` from the example, I see the warning:

```
Warning: Failed propType: Required prop `path` was not specified in `App`. Check the render method of `Connect(App)`.
```

**Comment by bdefore** [comment]
Ah, I see my issue. It's no longer on the reducer as `path` but `location`, which is an object with `pathname`, `query`, `search` etc.

**Comment by bdefore** [comment]
Reopening, since an example here or updated docs would still help.

**Comment by iyn** [comment]
I can't get `redux-simple-router` working with the `react-router` 2.0. I'm using `hashHistory` and when I try to run `syncReduxAndRouter`:
```
syncReduxAndRouter(hashHistory, store);
```
I get an error:
```
Uncaught TypeError: (0 , _reduxSimpleRouter.syncReduxAndRouter) is not a function
```
So yeah, I'd also want to see example how to use `redux-simple-router` with the latest router ;).

**Comment by SimenB** [comment]
`syncReduxAndRouter ` is removed, use `const router = syncHistory(hashHistory);` and `router.syncHistoryToStore(store);`

**Comment by bryce-larson** [comment]
+1

**Comment by iyn** [comment]
@SimenB: thanks!

**Comment by contra** [comment]
It would be cool if there was documentation for the latest version (2.x release)

**Comment by jlongster** [comment]
@contra There's a PR to update it (waiting for them to change something) and once it's merged I'll officially release 2.0.0 and make sure everything is up-to-date.
